### PR TITLE
Update the content

### LINKED ISSUE #20: Update the website content
The content of the website is now very old and ~1 Year old, we would require to update them as soon as possible

Following files should be updated,
- [x] [Clublife.yaml](https://github.com/amfoss/website/blob/master/src/content/clubLife.yaml)
- [x] [Story.yaml](https://github.com/amfoss/website/blob/master/src/content/story.yaml)
- [ ] [homeSections.yaml](https://github.com/amfoss/website/blob/master/src/content/homeSections.yaml)
- [ ] [whyJoin.yaml](https://github.com/amfoss/website/blob/master/src/content/whyJoin.yaml)

### PR DESCRIPTION
**Pull request by akhilam512**
Hi,

The content of the pages wasn't organised and was really old,

With this patchset, it partly fixes #20 

Advances #20

### CODE REVIEW

**Review by vibhoothi — CHANGES_REQUESTED** [review]
Hi,

Thank you for the patch, please split the patch into two commits.

**Comment by akhilam512** [comment]
> Hi,
> 
> Thank you for the patch, please split the patch into two commits.

Hi,

I split it, is it fine now?

**Comment by vibhoothi** [comment]
Not really, please make the commit message proper

**Review by vibhoothi — APPROVED** [review]
LGTM

**Pull request merged**
